### ISSUE TITLE
Docs for upgrades?

### ISSUE THREAD

**Issue by carldanley** [kelseyhightower/kubernetes-the-hard-way#205] opened 2017-08-31 21:26 UTC
Hello!

I intend on going through this tutorial sometime in the near future and spent some time reading through each of the docs for the time being. I was wondering: are there plans to add documentation about upgrading the components... the hard way?

**Comment by kelseyhightower** [comment] 2017-09-01 02:45
@carldanley I've thought about it. I know the flow and I really need to see how much would it would be. I can see this being a dedicated lab: stop this service, copy this binary, restart this service -- in a specific order. The problem is around having to migrate from alpha objects, but we could leave that out of scope.

**Comment by carldanley** [comment] 2017-09-01 02:49
Yeah, agreed. I think it's really easy to get off track regarding upgrading (as there are plenty of things to be covered). Though, having some initial documentation that covers the upgrade as a lab would be **really** nice. Even to touch on the parts that get upgraded, etc, etc.

**Comment by kelseyhightower** [comment] 2017-12-18 15:43
After going back and forth on this, I'm not sure I can add and maintain such a section at the moment. I might revisit this later.

**Closed by kelseyhightower** 2017-12-18 15:43 UTC

**Comment by carldanley** [comment] 2017-12-18 15:44
Understood! Thanks ;)
