### ISSUE TITLE
issue while Generate the CA certificate and private key:

### ISSUE THREAD

**Issue by szanwar1** [kelseyhightower/kubernetes-the-hard-way#326] opened 2018-03-06 00:15 UTC
cfssl gencert -initca ca-csr.json | cfssljson -bare ca
failed MSpanList_Insert 0x246000 0x4a2f266c8f08 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x15d320, 0x10)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0x7ffeefbff5d0 sp=0x7ffeefbff5b8
runtime.(*mSpanList).insert(0x1fdee8, 0x246000)
	/usr/local/go/src/runtime/mheap.go:933 +0x293 fp=0x7ffeefbff600 sp=0x7ffeefbff5d0
runtime.(*mheap).freeSpanLocked(0x1fd6e0, 0x246000, 0x100, 0x0)
	/usr/local/go/src/runtime/mheap.go:809 +0x4be fp=0x7ffeefbff668 sp=0x7ffeefbff600
runtime.(*mheap).grow(0x1fd6e0, 0x8, 0x0)
	/usr/local/go/src/runtime/mheap.go:675 +0x2a0 fp=0x7ffeefbff6c0 sp=0x7ffeefbff668
runtime.(*mheap).allocSpanLocked(0x1fd6e0, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:553 +0x4e3 fp=0x7ffeefbff718 sp=0x7ffeefbff6c0
runtime.(*mheap).alloc_m(0x1fd6e0, 0x1, 0x15, 0x0)
	/usr/local/go/src/runtime/mheap.go:437 +0x119 fp=0x7ffeefbff748 sp=0x7ffeefbff718
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41 fp=0x7ffeefbff778 sp=0x7ffeefbff748
runtime.systemstack(0x7ffeefbff798)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff780 sp=0x7ffeefbff778
runtime.(*mheap).alloc(0x1fd6e0, 0x1, 0x10000000015, 0x108df)
	/usr/local/go/src/runtime/mheap.go:503 +0x63 fp=0x7ffeefbff7c8 sp=0x7ffeefbff780
runtime.(*mcentral).grow(0x1ff2e0, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93 fp=0x7ffeefbff830 sp=0x7ffeefbff7c8
runtime.(*mcentral).cacheSpan(0x1ff2e0, 0x1fa308)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d fp=0x7ffeefbff870 sp=0x7ffeefbff830
runtime.(*mcache).refill(0x242000, 0x15, 0x7ffeefbff8d8)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc fp=0x7ffeefbff8a8 sp=0x7ffeefbff870
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b fp=0x7ffeefbff8c8 sp=0x7ffeefbff8a8
runtime.systemstack(0x7ffeefbff968)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff8d0 sp=0x7ffeefbff8c8
runtime.mallocgc(0x180, 0x140400, 0x0, 0x800000000)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0x7ffeefbff9a8 sp=0x7ffeefbff8d0
runtime.newobject(0x140400, 0x1fa5b0)
	/usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0x7ffeefbff9d0 sp=0x7ffeefbff9a8
runtime.malg(0x8000, 0x1fa820)
	/usr/local/go/src/runtime/proc.go:2634 +0x27 fp=0x7ffeefbffa08 sp=0x7ffeefbff9d0
runtime.mpreinit(0x1fab60)
	/usr/local/go/src/runtime/os1_darwin.go:140 +0x1f fp=0x7ffeefbffa20 sp=0x7ffeefbffa08
runtime.mcommoninit(0x1fab60)
	/usr/local/go/src/runtime/proc.go:494 +0x105 fp=0x7ffeefbffa68 sp=0x7ffeefbffa20
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:434 +0x79 fp=0x7ffeefbffab0 sp=0x7ffeefbffa68
runtime.rt0_go(0x7ffeefbffae0, 0x3, 0x7ffeefbffae0, 0x0, 0x3, 0x7ffeefbffc10, 0x7ffeefbffc1a, 0x7ffeefbffc20, 0x0, 0x7ffeefbffc23, ...)
	/usr/local/go/src/runtime/asm_amd64.s:138 +0x132 fp=0x7ffeefbffab8 sp=0x7ffeefbffab0
2018/03/05 16:10:01 [INFO] generating a new CA key and certificate from CSR
2018/03/05 16:10:01 [INFO] generate received request
2018/03/05 16:10:01 [INFO] received CSR
2018/03/05 16:10:01 [INFO] generating key: rsa-2048
2018/03/05 16:10:01 [INFO] encoded CSR
2018/03/05 16:10:01 [INFO] signed certificate with serial number 187259040120345663613119893646474160081797649024

**Comment by hareeshrao4839** [comment] 2018-03-22 08:05
can you please check below mentioned files JSON format or not 
 ca-config.json and ca-csr.json 

Note: if its any annotations/ space's  mistakes, then  above Mentioned error Occures
if any ref of JSON Syntax check s use https://www.json2yaml.com/

**Comment by kelseyhightower** [comment] 2018-05-13 03:32
I can't reproduce this issue. Closing.

**Closed by kelseyhightower** 2018-05-13 03:32 UTC

**Comment by spursy** [comment] 2019-03-18 06:46
@hareeshrao4839 I have reproduced the same issue. Did you resolve this issue?

**Comment by jwalters-gpsw** [comment] 2019-04-02 14:15
Same

**Comment by inter-faced** [comment] 2019-04-07 14:36
I had the same issue. Resolved it by installing cfssl via brew as described here: https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/229#issuecomment-354332045
