### ISSUE TITLE
Worker nodes not connecting to controllers

### ISSUE THREAD

**Issue by 0xCMP** [kelseyhightower/kubernetes-the-hard-way#53] opened 2016-09-12 15:56 UTC
Cluster is running but when I tried to run `kubectl get nodes` I get nothing.

```
ubuntu@ip-10-240-0-32:~$ sudo systemctl status kubelet --no-pager -l
sudo: unable to resolve host ip-10-240-0-32
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2016-09-12 15:25:18 UTC; 29min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 4826 (kubelet)
   CGroup: /system.slice/kubelet.service
           ├─4826 /usr/bin/kubelet --allow-privileged=true --api-servers=https://10.240.0.20:6443,https://10.240.0.21:6443,https://10.240.0.22:6443 --cloud-provider= --cluster-dns=10.32.0.10 --cluster-domain=cluster.local --configure-cbr0=true --container-runtime=docker --docker=unix:///var/run/docker.sock --network-plugin=kubenet --kubeconfig=/var/lib/kubelet/kubeconfig --reconcile-cidr=true --serialize-image-pulls=false --tls-cert-file=/var/lib/kubernetes/kubernetes.pem --tls-private-key-file=/var/lib/kubernetes/kubernetes-key.pem --v=2
           └─4926 journalctl -k -f

Sep 12 15:54:07 ip-10-240-0-32 kubelet[4826]: E0912 15:54:07.792577    4826 kubelet.go:1193] Unable to construct api.Node object for kubelet: can't get ip address of node ip-10-240-0-32: lookup ip-10-240-0-32 on 10.240.0.2:53: no such host
Sep 12 15:54:08 ip-10-240-0-32 kubelet[4826]: I0912 15:54:08.966674    4826 kubelet.go:2510] skipping pod synchronization - [Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
Sep 12 15:54:13 ip-10-240-0-32 kubelet[4826]: I0912 15:54:13.967726    4826 kubelet.go:2510] skipping pod synchronization - [Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
Sep 12 15:54:14 ip-10-240-0-32 kubelet[4826]: E0912 15:54:14.795108    4826 kubelet.go:1193] Unable to construct api.Node object for kubelet: can't get ip address of node ip-10-240-0-32: lookup ip-10-240-0-32 on 10.240.0.2:53: no such host
Sep 12 15:54:18 ip-10-240-0-32 kubelet[4826]: I0912 15:54:18.972411    4826 kubelet.go:2510] skipping pod synchronization - [Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
Sep 12 15:54:21 ip-10-240-0-32 kubelet[4826]: E0912 15:54:21.829771    4826 kubelet.go:1193] Unable to construct api.Node object for kubelet: can't get ip address of node ip-10-240-0-32: lookup ip-10-240-0-32 on 10.240.0.2:53: no such host
Sep 12 15:54:23 ip-10-240-0-32 kubelet[4826]: I0912 15:54:23.973540    4826 kubelet.go:2510] skipping pod synchronization - [Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
Sep 12 15:54:28 ip-10-240-0-32 kubelet[4826]: E0912 15:54:28.832401    4826 kubelet.go:1193] Unable to construct api.Node object for kubelet: can't get ip address of node ip-10-240-0-32: lookup ip-10-240-0-32 on 10.240.0.2:53: no such host
Sep 12 15:54:28 ip-10-240-0-32 kubelet[4826]: I0912 15:54:28.974251    4826 kubelet.go:2510] skipping pod synchronization - [Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
Sep 12 15:54:33 ip-10-240-0-32 kubelet[4826]: I0912 15:54:33.974961    4826 kubelet.go:2510] skipping pod synchronization - [Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
ubuntu@ip-10-240-0-32:~$
```

```
ubuntu@ip-10-240-0-32:~$ sudo systemctl status kube-proxy --no-pager -l
sudo: unable to resolve host ip-10-240-0-32
● kube-proxy.service - Kubernetes Kube Proxy
   Loaded: loaded (/etc/systemd/system/kube-proxy.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2016-09-12 15:25:18 UTC; 29min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 4891 (kube-proxy)
   CGroup: /system.slice/kube-proxy.service
           └─4891 /usr/bin/kube-proxy --master=https://10.240.0.20:6443 --kubeconfig=/var/lib/kubelet/kubeconfig --proxy-mode=iptables --v=2

Sep 12 15:25:18 ip-10-240-0-32 kube-proxy[4891]: W0912 15:25:18.818446    4891 server.go:416] Failed to retrieve node info: nodes "ip-10-240-0-32" not found
Sep 12 15:25:18 ip-10-240-0-32 kube-proxy[4891]: W0912 15:25:18.818512    4891 proxier.go:227] invalid nodeIP, initialize kube-proxy with 127.0.0.1 as nodeIP
Sep 12 15:25:18 ip-10-240-0-32 kube-proxy[4891]: I0912 15:25:18.818524    4891 server.go:214] Tearing down userspace rules.
Sep 12 15:25:18 ip-10-240-0-32 kube-proxy[4891]: I0912 15:25:18.831959    4891 conntrack.go:40] Setting nf_conntrack_max to 32768
Sep 12 15:25:18 ip-10-240-0-32 kube-proxy[4891]: I0912 15:25:18.833675    4891 conntrack.go:57] Setting conntrack hashsize to 8192
Sep 12 15:25:18 ip-10-240-0-32 kube-proxy[4891]: I0912 15:25:18.833906    4891 conntrack.go:62] Setting nf_conntrack_tcp_timeout_established to 86400
Sep 12 15:25:18 ip-10-240-0-32 kube-proxy[4891]: I0912 15:25:18.837957    4891 proxier.go:440] Adding new service "default/kubernetes:https" at 10.32.0.1:443/TCP
Sep 12 15:25:18 ip-10-240-0-32 kube-proxy[4891]: I0912 15:25:18.838227    4891 proxier.go:674] Not syncing iptables until Services and Endpoints have been received from master
Sep 12 15:25:18 ip-10-240-0-32 kube-proxy[4891]: I0912 15:25:18.839653    4891 proxier.go:516] Setting endpoints for "default/kubernetes:https" to [10.240.0.20:6443 10.240.0.21:6443 10.240.0.22:6443]
Sep 12 15:35:48 ip-10-240-0-32 systemd[1]: Started Kubernetes Kube Proxy.
ubuntu@ip-10-240-0-32:~$
```

Something is wrong with the hostname setup of my worker node it seems. It can't get a valid IP for itself.

**Comment by cmpis** [comment] 2016-09-12 16:01
Yea updated `/etc/hosts` with the internal IP. Not sure why it's not resolving on its own. Has been causing issues with sudo as well giving errors resolving the hostname.

**Comment by kelseyhightower** [comment] 2016-09-12 16:11
@cmpis Thanks for reporting this issue. I wonder if you enabled all the dns stuff from the AWS infra provisioning guide?

I've worked through the docs a few times, but maybe I'm missing something.

**Comment by cmpis** [comment] 2016-09-12 16:27
I'm not sure, but it causes issues in the smoke test as well. My changes to the hosts file make it so kube-proxy doesn't properly expose the nginx container. So clearly what I did doesn't truly fix it.

**Comment by cmpis** [comment] 2016-09-12 16:31
I checked in my history and I did run the DHCP and the VPC DNS setup commands. But I think the issue is I setup my cluster in `us-east-1` and I didn't update the DHCP option. Must have missed that.

**Comment by kelseyhightower** [comment] 2016-09-12 19:08
@cmpis Let me know if adding the DHCP option fixes things.

**Comment by cmpis** [comment] 2016-09-13 22:48
Ah, sorry, I deleted the cluster I had. I'm almost certain that would have fixed it because I was seeing DNS issues the whole time. 

Maybe I'll contribute a warning to that area incase someone else makes the same mistake in `us-east-1`

**Comment by michaeld** [comment] 2016-10-08 22:43
I'm struggling with this issue on AWS as well.

What's at 10.32.0.10 `--cluster-dns=10.32.0.10`? I didn't see this address created in any previous steps?

**Comment by vlad-vintila-hs** [comment] 2016-10-10 13:21
> What's at 10.32.0.10 --cluster-dns=10.32.0.10? I didn't see this address created in any previous steps?

It's the DNS service created in https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-dns-addon.md 
You won't find it added anywhere at AWS level since it's a virtualIP made to work by kube-proxy http://kubernetes.io/docs/user-guide/services/#virtual-ips-and-service-proxies

**Comment by metadave** [comment] 2016-11-14 21:57
stung by the same bug in `us-east-1`:

```
ε 16:23:54 ~$ kubectl get componentstatuses
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-1               Healthy   {"health": "true"}
etcd-2               Healthy   {"health": "true"}
etcd-0               Healthy   {"health": "true"}
ε 16:24:01 ~$ kubectl get nodes
ε 16:24:13 ~$
```

I tried using the following during install (it didn't work for me, read below):

```
DHCP_OPTION_SET_ID=$(aws ec2 create-dhcp-options \
  --dhcp-configuration "Key=domain-name,Values=us-east-1.compute.internal" \
    "Key=domain-name-servers,Values=AmazonProvidedDNS" | \
  jq -r '.DhcpOptions.DhcpOptionsId')
```

Using `us-east-1.compute.internal` was incorrect, as [this AWS page](http://docs.aws.amazon.com/cli/latest/reference/ec2/create-dhcp-options.html) points out. If you're trying the tutorial in `us-east-1`, I believe that you'll need to use `ec2.internal` as the param to `domain-name`, although I probably won't be able to get back to trying it for some time.

**Comment by wjessop** [comment] 2016-11-25 22:03
I have the same issue, but I am using us-west-2

**Comment by danielfn** [comment] 2016-12-30 08:40
I came across with this same problem while testing OpenShift in AWS, and it's probably related with this bug in Go:
https://github.com/golang/go/issues/17967

**Comment by ruxandraburtica** [comment] 2017-03-24 15:50
@metadave @wjessop @michaeld can you double check that #134 (add ``--cloud-provider=aws`` in the ``kubelet.service`` unit file's [Service] section and restarting `kubelet` afterwards - `sudo systemctl restart kubelet` ) fixes it?

**Comment by kelseyhightower** [comment] 2017-03-26 02:41
I've decided to focus on a single platform for this guide. I'm shifting focus to cover more configuration options such as RBAC, TLS bootstrapping, and add-ons. Too much time required to keep the IaaS bits in sync with AWS.

I also don't plan to add support for any cloud provider integration to keep this guide simple and a little more reusable for other platforms.

**Closed by kelseyhightower** 2017-03-26 02:41 UTC
